server:
  port: 8001

spring:
  profiles: default
  datasource:
    url: jdbc:mysql://mysql:3306/UserSOA
    username: user
    password: root
    useSSL: false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      useSSL: false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    nonSecurePortEnabled: true
    nonSecurePort: 8761
    hostname: eureka-service.test.svc
    homePageUrl: http://${eureka.instance.hostname}/
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
